export default {
  production: {
    gatewayShortDomain: "sephora-soa-api-gateway",
    restfulEnv: "production",
    localhost: "m.sephora.cn",
    static: "https://ssl1.sephorastatic.cn",
    staticUnSsl: "http://s1.sephorastatic.cn",
    abtest: "https://m.sephora.cn",
    newtest: "https://m.sephora.cn",
    api: "api.sephora.cn",
    nodeServer: "http://sephora-soa-api-gateway",
    seo: "dppvcmswem.sephora.cn/api/gettdk.php",
  },
  ebf: {
    gatewayShortDomain: "ebf-sephora-soa-api-gateway",
    restfulEnv: "ebf",
    localhost: "m.sephora.cn",
    static: "https://sslstage1.sephorastatic.cn",
    staticUnSsl: "http://s1.sephorastatic.cn",
    abtest: "https://m.sephora.cn",
    newtest: "https://ebfm.sephora.cn",
    api: "ebfapi.sephora.cn",
    nodeServer: "http://ebf-sephora-soa-api-gateway",
    seo: "dpsvcmswem.sephora.cn/api/gettdk.php",
  },
  stage: {
    gatewayShortDomain: "stage-sephora-soa-api-gateway",
    restfulEnv: "stage",
    localhost: "stagem.sephora.cn",
    static: "https://sslstage1.sephorastatic.cn",
    staticUnSsl: "http://stage1.sephorastatic.cn",
    abtest: "https://stagem.sephora.cn",
    newtest: "https://stagem.sephora.cn",
    api: "stageapi.sephora.cn",
    nodeServer: "http://stage-sephora-soa-api-gateway",
    seo: "dpsvcmswem.sephora.cn/api/gettdk.php",
  },
  qa1: {
    gatewayShortDomain: "qa1-sephora-soa-api-gateway",
    restfulEnv: "qa1",
    localhost: "qa1.sephora.cn",
    static: "https://sslstage1.sephorastatic.cn",
    staticUnSsl: "http://stage1.sephorastatic.cn",
    abtest: "https://testm.sephora.cn",
    newtest: "https://testm.sephora.cn",
    api: "testapi.sephora.cn",
    nodeServer: "http://qa1-sephora-soa-api-gateway",
    seo: "dpsvcmswem.sephora.cn/api/gettdk.php",
  },
  qa2: {
    gatewayShortDomain: "qa2-sephora-soa-api-gateway",
    restfulEnv: "qa2",
    localhost: "qa2.sephora.cn",
    static: "https://sslstage1.sephorastatic.cn",
    staticUnSsl: "http://stage1.sephorastatic.cn",
    abtest: "https://testm.sephora.cn",
    newtest: "https://testm.sephora.cn",
    api: "testapi.sephora.cn",
    nodeServer: "http://qa2-sephora-soa-api-gateway",
    seo: "dpsvcmswem.sephora.cn/api/gettdk.php",
  },
} as {
  [K: string]: SephoraConfig;
};
