export default {
  myAccountInfo: {
    photo: '',
    nickname: '',
    profilePageUrl: '/myAccount/profile.html',
    isEnjoyMent: {
      state: 1,
      imageUrl: [
        'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/isBeautyKol.png',
        'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/beautyKol.png',
      ],
    },
    setUp: '/myAccount/management',
    setUpImageUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/setup.png',
    myNewsImageUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/myMeaasge.png',
    myNewsCount: false,
    myNewsLink: '/myAccount/myMessage?type=0',
    integralRecordUrl: 'changePointStstus',
    cardPoints: '',
    cardBenefitsInfo: '',
    couponCounts: '',
    couponUrl: '/myAccount/myCoupon',
    cardImageUrl: '',
    cardLevel: '',
    memberCardUrl: 'isAllowEnterMember',
    userProfileAdPosition: '',
    upgradeProcess: '',
    cardInfoClass: true,
    cardTypeMapping: {
      PINK: '粉卡会员',
      WHITE: '白卡会员',
      BLACK: '黑卡会员',
      GOLDEN: '金卡会员',
      EMPLOYEE: '员工账号',
      TEST: '测试账号',
      O2O: 'BA账号',
      BACKEND: '无卡会员',
    },
    cardImage: {
      PINK: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/new_pinkVip.png',
      WHITE: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/new_whiteVip.png',
      BLACK: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/new_blackVip.png',
      GOLDEN: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/new_glodenVip.png',
      EMPLOYEE: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/defalut_card.png',
      TEST: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/defalut_card.png',
      O2O: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/defalut_card.png',
      BACKEND: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/defalut_card.png',
    },
    userGroup: ['PINK', 'WHITE', 'BLACK', 'GOLDEN'],
  },
  order: [
    {
      content: '',
      name: '待支付',
      iconClass: '',
      href: '/myOrderList?orderType=DPP',
      key: 'DPP',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/ic_to_pay.png',
      moreClass: '',
      SensorName: '我的订单-待支付',
    },
    {
      content: '',
      name: '待发货',
      iconClass: '',
      href: '/myOrderList?orderType=DIP',
      key: 'DIP',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/ic_in_deal.png',
      moreClass: '',
      SensorName: '我的订单-待发货',
    },
    {
      content: '',
      name: '已发货',
      iconClass: '',
      href: '/myOrderList?orderType=DID',
      key: 'DID',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/ic_in_delievery.png',
      moreClass: '',
      SensorName: '我的订单-已发货',
    },
    {
      content: '',
      name: '待评价',
      iconClass: '',
      href: '/myOrderList?orderType=DF',
      key: 'DF',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/ic_deal_complete.png',
      moreClass: '',
      SensorName: '我的订单-待评价',
    },
    {
      content: '',
      name: '退货/售后',
      iconClass: '',
      href: '/myAccount/returnList',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/newReturn.png',
      SensorName: '我的订单-退货/售后',
    },
  ],
  tool: [
    {
      name: '预约中心',
      iconClass: '',
      href: 'https://wx.sephora.cn/v2/html5/online-booking-app/index.html',
      callbackKEY: '',
      content: '',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/reservationcenter.png',
      SensorName: '玩美服务-预约中心',
    },
    {
      name: '申领中心',
      iconClass: '',
      href: '',
      callbackKEY: 'claimcenter',
      content: '',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/claimcenter.png',
      SensorName: '玩美服务-申领中心',
    },
    {
      name: '在线客服',
      iconClass: '',
      href: '',
      callbackKEY: 'startCustomerService',
      content: '',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/onlineService.png',
      SensorName: '玩美服务-在线客服',
    },
    {
      name: '帮助中心',
      iconClass: '',
      href: '/helpInfo/',
      content: '',
      imgUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/helpCenter.png',
      SensorName: '玩美服务-帮助中心',
    },
  ],
  guideImageList: [
    'https://ssl1.sephorastatic.cn/soa/nmobile/img/guide_step1.png',
    'https://ssl1.sephorastatic.cn/soa/nmobile/img/guide_step2.png',
    'https://ssl1.sephorastatic.cn/soa/nmobile/img/guide_step3.png',
    'https://ssl1.sephorastatic.cn/soa/nmobile/img/guide_step3_order.png',
  ],
};
