/**
 * INIT
 * @type {string}
 */

// 特效 nichefragrance
export const NICHEFRAGRANCE = {
  INDEX: "NICHEFRAGRANCE.INDEX",
  STATE: "NICHEFRAGRANCE.STATE",
  PRELOADIMG: "NICHEFRAGRANCE.PRELOADIMG",
};

// 三方数据 Emarsys
export const COMMONVENDERS = {
  EMARSYS_QUEUE: "COMMONVENDERS.EMARSYS_QUEUE",
};

// 获取设备信息
export const VIEW = {
  CLIENT_HEIGHT: "VIEW.CLIENT_HEIGHT",
  SCROLL_TOP: "VIEW.SCROLL_TOP",
};

// Common constant for ajax
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_RECEIVE = "FETCH_RECEIVE";
export const FETCH_ERROR = "FETCH_ERROR";

// 全局存储信息
export const GLOBALREFERENCE = {
  USER_SOCIALLOGIN: "GLOBALREFERENCE.USER_SOCIALLOGIN",
  USER_USERCARDINFO: "GLOBALREFERENCE.USER_USERCARDINFO",
  FINISH_PAGE_LOAD: "GLOBALREFERENCE.FINISH_PAGE_LOAD",
};

// 三方监控代码
export const DEPENDENCY = {
  GOOGLE_ANALYTICS: "DEPENDENCY.GOOGLE_ANALYTICS",
  WECHAT_JS_BRIDGE: "DEPENDENCY.WECHAT_JS_BRIDGE",
};
// GA 记录用户登录状态
export const GOOGLE_ANALYTICS = {
  USER: "GOOGLE_ANALYTICS.USER",
  PUSHV2: "GOOGLE_ANALYTICS.PUSHV2",
};

// SEARCH 搜索相关的数据
export const SEARCH = {
  GETHOTSEARCHWORD: "SEARCH.GETHOTSEARCHWORD",
  EXPAND_ISTRUE: "SEARCH.EXPAND_ISTRUE",
  HISTORY_BROWSING: "SEARCH.HISTORY_BROWSING",
  HISTORY_ARR: "SEARCH.HISTORY_ARR",
  IFINPUTTRUE: "SEARCH.IFINPUTTRUE",
};

export const DEVICE = {
  IS_WEIXIN: "DEVICE.IS_WEIXIN",
};

// 购物车业务所有KEY
export const CART = {
  QCPTQ: "CART.QCPTQ",
};

export const POPUP_COMPONENT = {
  POPUP_NORMAL: "POPUP_COMPONENT.POPUP_NORMAL",
  POPUP_ALERT: "POPUP_COMPONENT.POPUP_ALERT",
};

// 个人中心
export const MY_ACCOUNT = {
  MY_ACCOUNT_PROFILE: "MY_ACCOUNT.MY_ACCOUNT_PROFILE",
  MY_ACCOUNT_ORDERS: "MY_ACCOUNT.MY_ACCOUNT_ORDERS",
  MY_ACCOUNT_TOOLS: "MY_ACCOUNT.MY_ACCOUNT_TOOLS",
  MANAGEMENT_OPTIONS: "MY_ACCOUNT.MANAGEMENT_OPTIONS",
  MEMBER_INFO: "MY_ACCOUNT.MEMBER_INFO",
  INTEGRAL_FLOW: "MY_ACCOUNT.INTEGRAL_FLOW",
  MYMSG_TAP: "MY_ACCOUNT.MYMSG_TAP",
  MESSAGHE_LIST: "MY_ACCOUNT.MESSAGHE_LIST",
  OFFLINE_ORDER_LIST: "MY_ACCOUNT.OFFLINE_ORDER_LIST",
  MY_ACCOUNT_ORDERSWIPER: "MY_ACCOUNT_ORDERSWIPER",
  MY_ACCOUNT_INVOICELISTDATA: "MY_ACCOUNT_INVOICELISTDATA",
  MY_ACCOUNT_GUIDEIMAGE: "MY_ACCOUNT.MY_ACCOUNT_GUIDEIMAGE",
  MY_COUPON_HISTORY: "MY_ACCOUNT.MY_COUPON_HISTORY",
};

// 收货地址
export const MY_ADDRESS = {
  ALL_ADDRESSS: "MY_ADDRESS.ALL_ADDRESSS",
  ADDRESSS_STATUS: "MY_ADDRESS.ADDRESSS_STATUS",
  SAVE_PROVINCE_DATA: "MY_ADDRESS.SAVE_PROVINCE_DATA",
  CONTROL_PROVINCE: "MY_ADDRESS.CONTROL_PROVINCE",
  CURRENT_INDEX: "MY_ADDRESS.CURRENT_INDEX",
};

// 修改个人信息
export const MY_PROFILE = {
  PAGE_SHOW: "MY_PROFILE.PAGE_SHOW",
  PROFILE_INFO: "MY_PROFILE.PROFILE_INFO",
  CARD_LIST: "MY_PROFILE.CARD_LIST",
  USER_MOBILE: "MY_PROFILE.USER_MOBILE",
};
// 在线退货
export const MY_ONLINERETURN = {
  STATUS: "MY_ONLINERETURN.STATUS",
  RECORD_REASON: "MY_ONLINERETURN.RECORD_REASON",
  SAVE_APPLY_DATA: "MY_ONLINERETURN.SAVE_APPLY_DATA",
  RETURN_LIST_TAP: "MY_ONLINERETURN.RETURN_LIST_TAP",
  RETURN_LIST_DATA: "MY_ONLINERETURN.RETURN_LIST_DATA",
  RETURN_LIST_STATUS: "MY_ONLINERETURN.RETURN_LIST_STATUS",
  RETURN_DETAILS_DATA: "MY_ONLINERETURN.RETURN_DETAILS_DATA",
  RETURN_DETAILS_LOGISTICS: "MY_ONLINERETURN.RETURN_DETAILS_LOGISTICS",
  REFUND_DETAILS: "MY_ONLINERETURN.REFUND_DETAILS",
  APPLY_NOSCROLL: "MY_ONLINERETURN.APPLY_NOSCROLL",
};
//  强制更新密码
export const UPDATEPASSWORD = {
  SHOWHELP: "SHOWHELP",
  BODY: "BODY",
};
// 忘记密码
export const FORGOTTENPASSWORD = {
  SECONDSHOW: "SECONDSHOW",
  RTOKEN: "FORGOTTENPASSWORD.RTOKEN",
};
// register
export const REGISTER = {
  PAGE_STATUS: "REGISTER.PAGE_STATUS",
  CARD_LIST: "REGISTER.CARD_LIST",
  USER_INFO: "REGISTER.USER_INFO",
};

// login
export const LOGIN = {
  PAGE_STATUS: "LOGIN.PAGE_STATUS",
  LOGIN_SHOW_GRAPHIC: "LOGIN.LOGIN_SHOW_GRAPHIC",
  STORE_MEMBER_DATA: "LOGIN.STORE_MEMBER_DATA",
  STORE_PINK_CARD: "LOGIN.STORE_PINK_CARD",
  STORE_LOGIN_ID: "LOGIN.STORE_LOGIN_ID",
  STORE_CARD_NUM: "LOGIN.STORE_CARD_NUM",
  STORE_TIP: "LOGIN.STORE_TIP",
  NO_TITLE: "LOGIN.NO_TITLE",
  PERSONAL_INFO: "LOGIN.PERSONAL_INFO",
};

// product
export const PRODUCT = {
  VBLIST:"PRODUCT.VBLIST",
  TAB_INDEX: "PRODUCT.TAB_INDEX",
  TAB_INDEXV2: "PRODUCT.TAB_INDEXV2",
  TAB_MORE: "PRODUCT.TAB_MORE",
  DETAILS_TAP: "PRODUCT.DETAILS_TAP",
  DETAILS_DATA: "PRODUCT.DETAILS_DATA",
  COMMENTLIST: "PRODUCT.COMMENTLIST",
  INFO: "PRODUCT.INFO",
  BEAUTYPOSTS: "PRODUCT.BEAUTYPOSTS",
  SWIPER: "PRODUCT.SWIPER",
  CONSULATION: "PRODUCT.CONSULATION",
  RECOMMEND: "PRODUCT.RECOMMEND",
  SPECS: "PRODUCT.SPECS",
  RECORD_NOW_NUM: "PRODUCT.RECORD_NOW_NUM",
  LIPSTICKONOFF: "PRODUCT.LIPSTICKONOFF",
  LIPSTICKONOFF2: "PRODUCT.LIPSTICKONOFF2",
  LIPSTICKONOFF3: "PRODUCT.LIPSTICKONOFF3",
  ARRIVALNOTICE: "PRODUCT.ARRIVALNOTICE",
  IFCOMMENT: "PRODUCT.IFCOMMENT",
  SPECIAL_SKUID: "PRODUCT.SPECIAL_SKUID",
  CLOSE_PCIK_COLORS: "PRODUCT.CLOSE_PCIK_COLORS",
  QCPTQ: "QCPTQ",
  RANKING: "RANKING",
  PDP_FILTER_OPEN_PAGE: "PRODUCT.PDP_FILTER_OPEN_PAGE", // miumiu香水当前页
  PDP_PRODUCT_SKU_CUSTOM_MADE: "PRODUCT.PDP_PRODUCT_SKU_CUSTOM_MADE", // 获取miumiu香水初始数据
  PDP_PRODUCT_SKU_CUSTOM_MADE_TWO: "PRODUCT.PDP_PRODUCT_SKU_CUSTOM_MADE_TWO", // 第二步数据存储
  PDP_PRODUCT_SKU_CUSTOM_MADE_THREE:
    "PRODUCT.PDP_PRODUCT_SKU_CUSTOM_MADE_THREE", // 瓶盖瓶身数据存储
  PDP_PRODUCT_SKU_CUSTOM_MADE_COMB: "PRODUCT.PDP_PRODUCT_SKU_CUSTOM_MADE_COMB", // 瓶身瓶盖香水组合
  PDP_PRODUCT_PROMOTION_TAGS: "PRODUCT.PDP_PRODUCT_PROMOTION_TAGS",
  PDP_PRODUCT_PROMOTION_FAST: "PRODUCT.PDP_PRODUCT_PROMOTION_FAST", //运费
  PDP_PRODUCT_DEEPLINK_OPEN: "PDP_PRODUCT_DEEPLINK_OPEN", // deepLink弹窗是否打开
};

// quiz
export const QUIZ = {
  QUIZ_RESULTS: "QUIZ.QUIZ_RESULTS",
  QUIZ_SELECTDTO: "QUIZ.QUIZ_SELECTDTO",
};

export const HOMEPAGE = {
  UPDATE_HOME_SESSION1: "UPDATE_HOME_SESSION1",
  UPDATE_TAB: "UPDATE_TAB",
};

// 积分商城
export const REWARD = {
  RULESHOW: "REWARD.RULESHOW",
};
// Category
export const CATEGORY = {
  CATEGORY_SEARCH: "CATEGORY.CATEGORY_SEARCH",
  CATEGORY_MENU: "CATEGORY.CATEGORY_MENU",
  CATEGORY_RESULTS: "CATEGORY.CATEGORY_RESULTS",
  CATEGORY_IMG: "CATEGORY.CATEGORY_IMG", // category 图片广告位
};

export const PLPPAGE = {
  PRODUCTS: "CATEGORY.PRODUCTS",
  BRANDCON: "CATEGORY.BRANDCON",
  OBTAINDATA: "CATEGORY.OBTAINDATA",
};
// Innovation - APP/MOB/MNP礼品智能推荐(Phase 1)
export const GIFTINTELLIGENT = {
  RECOMMENDRESULT: "GIFTINTELLIGENT.RECOMMENDRESULT",
  GIFTLIST: "GIFTINTELLIGENT.GIFTLIST",
  SELECTRESDATA: "GIFTINTELLIGENT.SELECTRESDATA",
  QUESTIONCODE: "GIFTINTELLIGENT.QUESTIONCODE",
  ANSWERDTOS: "GIFTINTELLIGENT.ANSWERDTOS",
  ANIMATEJSON:"GIFTINTELLIGENT.ANIMATEJSON"
};
// Innovation - APP/MOB/MNP礼品智能推荐(Phase 2)
export const GIFTINTELLIGENT_2 = {
  RECOMMENDRESULT: "GIFTINTELLIGENT.RECOMMENDRESULT",
  GIFTLIST: "GIFTINTELLIGENT.GIFTLIST",
  SELECTRESDATA: "GIFTINTELLIGENT.SELECTRESDATA",
  QUESTIONCODE: "GIFTINTELLIGENT.QUESTIONCODE",
  ANSWERDTOS: "GIFTINTELLIGENT.ANSWERDTOS"
};

// 优惠券
export const MY_ACCOUNT_COUPON = {
  MY_ACCOUNT_COUPON: "MY_ACCOUNT_COUPON.MY_ACCOUNT_COUPON",
  MY_ACCOUNT_HISTORY_COUPON:"MY_ACCOUNT_COUPON.MY_ACCOUNT_HISTORY_COUPON",
  MY_DOOR_COUPON:"MY_ACCOUNT_COUPON.MY_DOOR_COUPON"
};
// 订单模块
//OrderList
export const ORDERLISTSTATUS = "ORDERLIST_STATUS"; //订单状态
export const ORDERLIST = {
  ORDERLIST_ALL: "ORDERLIST.ORDERLIST_ALL", //全部
  ORDERLIST_M: "ORDERLIST.ORDERLIST_M", //待支付
  ORDERLIST_I: "ORDERLIST.ORDERLIST_I", //处理中
  ORDERLIST_S: "ORDERLIST.ORDERLIST_S", //配送中
  ORDERLIST_D: "ORDERLIST.ORDERLIST_D", //已签收
  ORDERLIST_DPPB: "ORDERLIST.ORDERLIST_DPPB", //未支付定金预售尾款订单
  ORDERLIST_SHOW: "ORDERLIST.ORDERLIST_SHOW",
  ORDERLIST_PAY_ORDERID: "ORDERLIST.ORDERLIST_PAY_ORDERID", //支付orderId
  ORDERLIST_PAY_METHOD: "ORDERLIST.ORDERLIST_PAY_METHOD", //支付方式
  ORDERLIST_PAY_TYPE: "ORDERLIST.ORDERLIST_PAY_TYPE", //订单类型
  SAVECOUPON: "ORDERLIST.SAVECOUPON", //存储可用的优惠券
  SAVEUNCOUPON: "ORDERLIST.SAVEUNCOUPON", //存储不可用的优惠券
  DISTINGUISH_TYPE: "ORDERLIST.DISTINGUISH_TYPE", //判别输入类型
  GET_PERSONAL_INFO: "ORDERLIST.GET_PERSONAL_INFO", //获取用户个人信息
  SAVE_PERSONAL_CARD: "ORDERLIST.SAVE_PERSONAL_CARD", //个人信息页存储卡信息
  SAVE_PERSONAL_PHONE: "ORDERLIST.SAVE_PERSONAL_PHONE", //个人信息页存储输入手机号
  DISCRIMINANT_SOURCE: "ORDERLIST.DISCRIMINANT_SOURCE", //选卡后判别是更改密码还是更改手机
  LOGIN_KEEP_USERID: "ORDERLIST.LOGIN_KEEP_USERID", //门店会员首次登陆记录ueserId
  LOGIN_KEEP_CARD_MESSAGE: "ORDERLIST.LOGIN_KEEP_CARD_MESSAGE", //门店会员首次登陆记录卡信息
  LOGIN_KEEP_MOBILE: "ORDERLIST.LOGIN_KEEP_MOBILE", //门店会员首次登陆输入手机号
  LOGIN_KEEP_PINK_CARD: "ORDERLIST.LOGIN_KEEP_PINK_CARD", //门店会员首次登陆领取粉卡
  LOGIN_KEEP_CARD_NUM: "ORDERLIST.LOGIN_KEEP_CARD_NUM", //门店会员首次登陆记录卡号
  FIRST_POPUP: "ORDERLIST.FIRST_POPUP", //进入首页显示popup
  SAVE_CHANGE_CARD_LIST: "ORDERLIST.SAVE_CHANGE_CARD_LIST", //用户换卡 -- 存储卡列表
  SAVE_CHANGE_CARD_PHONE_OR_EMAIL: "ORDERLIST.SAVE_CHANGE_CARD_PHONE_OR_EMAIL", //用户换卡 -- 存储登陆的手机或者邮箱
  SAVE_CHANGE_CARD_EMAIL: "ORDERLIST.SAVE_CHANGE_CARD_EMAIL", //用户换卡 -- 邮箱
  SAVE_CHANGE_CARD_SINGAL: "ORDERLIST.SAVE_CHANGE_CARD_SINGAL", //用户换卡 -- 绑定过手机直接回到会员卡介绍页
  LOGIN_KEEP_CARD_SOURCE: "ORDERLIST.LOGIN_KEEP_CARD_SOURCE", //门店会员记录卡来源
  LOGIN_PERSONAL_INFO: "ORDERLIST.LOGIN_PERSONAL_INFO", //手机验证码登陆保存个人信息
  CLICK_IS_POPUP: "ORDERLIST.CLICK_IS_POPUP", //用户点击了生日，昵称，手机，性别时触发popup提示
};
export const UNITECOOKIE = "UNITE_COOKIE"; //订单状态
export const PROTOTALMOUNT = "PROTOTALMOUNT"; //商品总价格
export const ORDERPAYCONFIRM = "ORDERPAYCONFIRM"; //展示确认定金模块
export const CANCLEORDERID = "CANCLEORDERID"; //取消订单
export const CANCLESTATUS = "CANCLESTATUS"; //取消订单来源
export const EDITBOOEL = "EDITBOOEL"; //定金预售产品编辑状态
