import getConfigs from "isomorphisms/getConfigs";

const config = getConfigs();

export default [
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/ATKINSONS_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/ATKINSONS.jpg`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/detail/ATKINSONS-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/detail/ATKINSONS-intro.png`,
    isLightColour: true,
    bgColor: "#ffffff",
    isFixedHeight: true,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/CHALING_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/CHALING.jpg`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/detail/CHALING-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/detail/CHALING-intro.png`,
    isLightColour: true,
    bgColor: "#f7f7f7",
    isFixedHeight: true,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/LACOME-placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/LACOME.jpg`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/detail/LACOME-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/detail/LACOME-intro.png`,
    isLightColour: true,
    bgColor: "#fbfbfb",
    isFixedHeight: true,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/atelierCologne_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/atelierCologne.png`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/brand/atelierCologne-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/brand/atelierCologne-intro.png`,
    isLightColour: true,
    bgColor: "#b32f23",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/acquadiparma_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/acquadiparma.png`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/brand/acquadiparma-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/brand/acquadiparma-intro.png`,
    isLightColour: false,
    bgColor: "#4a4748",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/guerlain_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/guerlain.png`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/brand/guerlain-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/brand/guerlain-intro.png`,
    isLightColour: true,
    bgColor: "#aecfe5",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/mm_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/mm.png`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/brand/mm-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/brand/mm-intro.png`,
    isLightColour: true,
    bgColor: "#f9f9f9",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/AC_main_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/AC_main.png`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/brand/ac_main_logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/brand/ac_main_intro.png`,
    isLightColour: false,
    bgColor: "#000000",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/MillerHarris_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/MillerHarris.jpg`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/detail/MillerHarris-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/detail/MillerHarris-intro.png`,
    isLightColour: false,
    bgColor: "#fcfdff",
    isFixedHeight: false,
  },
  {
    _mini: `${config.static}/soa/nmobile/img/nichefragrance/detail/chloe_placeholder.jpg`,
    _origin: `${config.static}/soa/nmobile/img/nichefragrance/detail/chloe.jpg`,
    _logo: `${config.static}/soa/nmobile/img/nichefragrance/detail/chloe-logo.png`,
    _intro: `${config.static}/soa/nmobile/img/nichefragrance/detail/chloe-intro.png`,
    isLightColour: false,
    bgColor: "#f3cfaf",
    isFixedHeight: false,
  },
];
