export default {
  userInfo: {
    photo: '',
    nickname: '',
    isComplete: '',
  },
  managementInfo: [
    {
      content: '',
      name: '管理收货地址',
      className: 'managementInfo managementInfo_address',
      iconUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/right-arrow-xi.png',
      href: '/myAccount/address',
      callbackKEY: '',
      usergroup: false,
      SensorName: '账号管理-管理收货地址',
    },
    {
      content: '',
      name: '更换会员卡',
      className: 'managementInfo managementInfo_change_card',
      iconUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/right-arrow-xi.png',
      href: '',
      callbackKEY: 'whetherChangeCard',
      usergroup: true,
      SensorName: '账号管理-更换会员卡',
    },
    {
      content: '',
      name: '更改登录密码',
      className: 'managementInfo managementInfo_change_password',
      iconUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/right-arrow-xi.png',
      href: '/myAccount/modifyPassword',
      callbackKEY: '',
      usergroup: false,
      SensorName: '账号管理-更改登录密码',
    },
    {
      content: '',
      name: '注销账户',
      className: 'managementInfo managementInfo_unsubscribe',
      iconUrl: 'https://ssl1.sephorastatic.cn/soa/nmobile/img/myAccount/right-arrow-xi.png',
      href: '',
      callbackKEY: 'unsubscribe',
      usergroup: false,
      SensorName: '账号管理-注销账户',
    },
  ],
};
